import React from 'react';
import { motion } from 'framer-motion';
import { BookOpen, Zap, Target, Search } from 'lucide-react';

export default function GeoGuide() {
  return (
    <div className="max-w-7xl mx-auto px-6 py-12">
      <div className="text-center max-w-3xl mx-auto mb-16">
        <h1 className="text-4xl md:text-5xl font-bold mb-6">The Complete Guide to Generative Engine Optimization (GEO)</h1>
        <p className="text-xl text-gray-400">
          Why GEO is becoming essential in the modern AI-powered internet, and how you can optimize your content to become a trusted reference within AI responses generated by systems like ChatGPT, Gemini, and Perplexity.
        </p>
      </div>

      <div className="space-y-16">
        <GuideSection 
          icon={<BookOpen />}
          title="What is GEO?"
          content="Generative Engine Optimization (GEO) is the process of optimizing your brand's online presence to be cited, recommended, and referenced by Large Language Models (LLMs) and AI-powered search engines. While traditional SEO focuses on ranking web pages in a list of links, GEO focuses on becoming the source of truth that AI systems use to generate direct answers for users."
        />
        <GuideSection 
          icon={<Zap />}
          title="Why GEO Matters Now"
          content="The way people discover information is fundamentally changing. Users are increasingly turning to AI assistants for complex queries, product recommendations, and research. If your brand isn't being cited in these AI-generated answers, you are losing visibility to competitors who have adapted to the generative search era. GEO ensures you remain visible and authoritative."
        />
        <GuideSection 
          icon={<Search />}
          title="How AI Systems Generate Answers"
          content="LLMs like ChatGPT and Perplexity analyze vast amounts of information to generate responses. They look for authoritative sources, structured data, clear facts, and high-quality content that directly answers the user's prompt. They prioritize information that is easy to parse, corroborated by other trusted sources, and presented without unnecessary fluff."
        />
        <GuideSection 
          icon={<Target />}
          title="Practical Steps for GEO Success"
          content="To succeed in GEO, you must shift your content strategy. Focus on answering specific, complex questions your audience is asking AI. Structure your data clearly using schema markup and JSON-LD. Provide verified facts and statistics. Build a strong brand narrative that AI systems can easily understand and reference. And most importantly, use tools like AnswerRank AI to track your citations and measure your progress."
        />
      </div>
    </div>
  );
}

function GuideSection({ icon, title, content }: { icon: React.ReactNode, title: string, content: string }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="glass-panel p-8 md:p-12 rounded-3xl border border-white/10"
    >
      <div className="flex items-center gap-6 mb-8">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-500/20 to-cyan-500/20 flex items-center justify-center text-purple-400">
          {icon}
        </div>
        <h2 className="text-3xl font-bold text-white">{title}</h2>
      </div>
      <p className="text-xl text-gray-400 leading-relaxed max-w-4xl">{content}</p>
    </motion.div>
  );
}
